# Generated by Django 4.0.2 on 2022-02-16 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='expire_in',
            new_name='expires_in',
        ),
    ]
